Repository likelion12-centralHackathon/Backend, pull requests merged in 2024-08, with the labels that each got.

#5 [Feature] add login,mypage
  .DS_Store
  .gitignore
  build.gradle
  gradle/gradle-daemon-jvm.properties
  gradlew.bat
  src/main/java/com/likelion/timer/login/auth/JwtAuthenticationFilter.java
  src/main/java/com/likelion/timer/login/auth/JwtProvider.java
  src/main/java/com/likelion/timer/login/auth/JwtUtil.java
  src/main/java/com/likelion/timer/login/auth/RestAuthenticationEntryPoint.java
  src/main/java/com/likelion/timer/login/auth/TokenAccessDeniedHandler.java
  src/main/java/com/likelion/timer/login/config/SecurityConfig.java
  src/main/java/com/likelion/timer/login/constant/AuthType.java
  src/main/java/com/likelion/timer/login/constant/GrantType.java
  src/main/java/com/likelion/timer/login/controller/LoginController.java
  src/main/java/com/likelion/timer/login/controller/TestController.java
  src/main/java/com/likelion/timer/login/dto/AuthTokenDto.java
  src/main/java/com/likelion/timer/login/dto/TokenDto.java
  src/main/java/com/likelion/timer/login/dto/reponse/ApiErrorResponse.java
  src/main/java/com/likelion/timer/login/dto/reponse/ApiResponse.java
  src/main/java/com/likelion/timer/login/dto/reponse/KakaoAuthResponse.java
  src/main/java/com/likelion/timer/login/dto/reponse/KakaoUserInfoResponse.java
  src/main/java/com/likelion/timer/login/exception/ApiException.java
  src/main/java/com/likelion/timer/login/exception/ApiExceptionHandler.java
  src/main/java/com/likelion/timer/login/exception/Error.java
  src/main/java/com/likelion/timer/login/model/RefreshToken.java
  src/main/java/com/likelion/timer/login/repository/RefreshTokenRepository.java
  src/main/java/com/likelion/timer/login/service/LoginService.java
  src/main/java/com/likelion/timer/login/util/RequestUtil.java
  src/main/java/com/likelion/timer/user/constant/GenderType.java
  src/main/java/com/likelion/timer/user/constant/UserStatus.java
  src/main/java/com/likelion/timer/user/controller/JoinController.java
  src/main/java/com/likelion/timer/user/controller/MyPageController.java
  src/main/java/com/likelion/timer/user/controller/UserController.java
  src/main/java/com/likelion/timer/user/dto/UserDto.java
  src/main/java/com/likelion/timer/user/dto/request/EditUserRequest.java
  src/main/java/com/likelion/timer/user/dto/request/KakaoJoinRequest.java
  src/main/java/com/likelion/timer/user/model/User.java
  src/main/java/com/likelion/timer/user/model/UserPrincipal.java
  src/main/java/com/likelion/timer/user/repository/UserRepository.java
  src/main/java/com/likelion/timer/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
Labels: enhancement

#6 [Feature] add timer api
  src/main/java/com/likelion/timer/TimerApplication.java
  src/main/java/com/likelion/timer/domain/Timer/constants/TimerConstants.java
  src/main/java/com/likelion/timer/domain/Timer/controller/TimerController.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/Part.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/PartImgUrl.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/PartList.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/Timer.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/PartListRepository.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/PartRepository.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/TimerRepository.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/PartReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/TimerReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/TimerUpdateReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/PartListResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerListResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/error/TimerErrorCode.java
  src/main/java/com/likelion/timer/domain/Timer/service/PartListService.java
  src/main/java/com/likelion/timer/domain/Timer/service/PartService.java
  src/main/java/com/likelion/timer/domain/Timer/service/TimerService.java
  src/main/java/com/likelion/timer/domain/User/domain/T_User.java
  src/main/java/com/likelion/timer/domain/User/domain/T_UserRepository.java
  src/main/java/com/likelion/timer/domain/model/PartTypeEnum.java
  src/main/java/com/likelion/timer/domain/model/TimerStateTypeEnum.java
  src/main/java/com/likelion/timer/global/entity/BaseTime.java
  src/main/java/com/likelion/timer/global/validation/MaxListSize.java
  src/main/java/com/likelion/timer/global/validation/MaxListSizeValidator.java
Labels: enhancement

#7 [Feature] add challenge CRUD api
  src/main/java/com/likelion/timer/challenge/entity/Bootchallenge.java
  src/main/java/com/likelion/timer/challenge/repository/ChallengeRepository.java
  src/main/java/com/likelion/timer/challenge/service/ChallengeService.java
  src/main/java/com/likelion/timer/controller/ChallengeController.java
  src/main/resources/templates/challengeList.html
  src/main/resources/templates/challengemodify.html
  src/main/resources/templates/challengeview.html
  src/main/resources/templates/challengewrite.html
  src/main/resources/templates/message.html
  src/main/resources/templates/participatingchallenges.html
Labels: enhancement

#8 [Feature] timer api 보완
  src/main/java/com/likelion/timer/domain/Timer/controller/TimerController.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/Timer.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/TimerRepository.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/service/TimerService.java
  src/main/java/com/likelion/timer/domain/User/domain/T_User.java
  src/main/java/com/likelion/timer/domain/User/domain/T_UserRepository.java
Labels: refactor

#14 Feature/streching
  .DS_Store
  src/main/java/com/likelion/timer/Youtube/AppConfig.java
  src/main/java/com/likelion/timer/Youtube/YoutubeApiController.java
  src/main/java/com/likelion/timer/login/config/SecurityConfig.java
  src/main/java/com/likelion/timer/login/config/WebConfig.java
  src/main/java/com/likelion/timer/user/model/User.java
  src/main/resources/templates/Videolist.js
  src/main/resources/templates/Videos.js
Labels: enhancement

#11 [Feature] add timer-fcm & mypage-timer api
  build.gradle
  src/main/java/com/likelion/timer/TimerApplication.java
  src/main/java/com/likelion/timer/domain/Timer/controller/TimerController.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/Part.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/PartList.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/RecordTimer.java
  src/main/java/com/likelion/timer/domain/Timer/domain/entity/Timer.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/PartRepository.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/RecordTimerRepository.java
  src/main/java/com/likelion/timer/domain/Timer/domain/repository/TimerRepository.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/RecordTimerReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/TimerReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/PartImgUrlsDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/PartStaticResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/RecordTimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerPartListResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/error/RecordTimerErrorCode.java
  src/main/java/com/likelion/timer/domain/Timer/error/TimerErrorCode.java
  src/main/java/com/likelion/timer/domain/Timer/service/RecordTimerService.java
  src/main/java/com/likelion/timer/domain/Timer/service/TimerService.java
  src/main/java/com/likelion/timer/domain/Timer/vo/MessageVo.java
  src/main/java/com/likelion/timer/domain/model/RecordTimerStateTypeEnum.java
  src/main/java/com/likelion/timer/domain/model/TimerStateTypeEnum.java
  src/main/java/com/likelion/timer/global/config/FCMConfig.java
  src/main/java/com/likelion/timer/global/util/DateUtil.java
  src/main/java/com/likelion/timer/global/util/FCMUtil.java
Labels: enhancement, chore

#16 [Refactor] 타이머 api 리팩토링
  src/main/java/com/likelion/timer/domain/Timer/controller/TimerController.java
  src/main/java/com/likelion/timer/domain/Timer/dto/req/RecordTimerReqDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/PartStaticResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/RecordTimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/dto/res/TimerResDto.java
  src/main/java/com/likelion/timer/domain/Timer/error/TimerErrorCode.java
  src/main/java/com/likelion/timer/domain/Timer/service/RecordTimerService.java
  src/main/java/com/likelion/timer/domain/Timer/service/TimerService.java
Labels: chore

#18 [Feature] bodysatisfaction api 추가
  src/main/java/com/likelion/timer/satisfatction/ApiResponse.java
  src/main/java/com/likelion/timer/satisfatction/ExceptionHandler.java
  src/main/java/com/likelion/timer/satisfatction/Satisfaction.java
  src/main/java/com/likelion/timer/satisfatction/SatisfactionController.java
  src/main/java/com/likelion/timer/satisfatction/SatisfactionRepository.java
  src/main/java/com/likelion/timer/satisfatction/SatisfactionRequest.java
  src/main/java/com/likelion/timer/satisfatction/SatisfactionResponse.java
  src/main/java/com/likelion/timer/satisfatction/SatisfactionService.java
  src/main/java/com/likelion/timer/user/dto/UserDto.java
Labels: enhancement

#21 [Feat] local.peroperties 값 숨기기
  .gitignore
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: documentation
